"""empty message

Revision ID: 36f12046b8fd
Revises: fccbbdf58c52
Create Date: 2021-10-03 10:24:32.296468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f12046b8fd'
down_revision = 'fccbbdf58c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('post_id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
